/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/test_bun.check" instead.
 */

#include <check.h>

#line 1 "tests/test_bun.check"
#include "../bun.h"
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <errno.h>

// --- Prologue ---

// Helper: terminate abnormally, after printing a message to stderr
void die(const char *fmt, ...)
{
  va_list args;
  va_start(args, fmt);

  fprintf(stderr, "fatal error: ");
  vfprintf(stderr, fmt, args);
  fprintf(stderr, "\n");

  va_end(args);

  abort();
}

// Helper: open a test fixture by name, relative to the tests/ directory.
static const char *fixture(const char *filename) {
    // For simplicity, tests assume they are run from the project root, and
    // test BUN files live in tests/fixtures/{valid,invalid}. Adjust if needed.
    static char path[256];
    int res = snprintf(path, sizeof(path), "tests/fixtures/%s", filename);
    if (res < 0) {
      die("snprintf failed: %s", strerror(errno));
    }
    if ((size_t) res > sizeof(path)) {
      die("filename '%s' too big for buffer (would write %d bytes to %zu-size buffer)",
          filename, res, sizeof(path));
    }
    return path;
}

// Helper: asserts invalid bun files
void assert_bun_status(const char* filename, bun_result_t expected) {
    BunParseContext ctx = {0};
    BunHeader header    = {0};

    bun_result_t r = bun_open(fixture(filename), &ctx);
    ck_assert_int_eq(r, BUN_OK);

    r = bun_parse_header(&ctx, &header);
    ck_assert_int_eq(r, expected);

    bun_close(&ctx);
}

// --- Tests ---

START_TEST(test_valid_minimal)
{
#line 57
    BunParseContext ctx = {0};
    BunHeader header    = {0};

    bun_result_t r = bun_open(fixture("valid/01-empty.bun"), &ctx);
    ck_assert_int_eq(r, BUN_OK);

    r = bun_parse_header(&ctx, &header);
    ck_assert_int_eq(r, BUN_OK);
    ck_assert_uint_eq(header.magic, BUN_MAGIC);
    ck_assert_uint_eq(header.version_major, 1);
    ck_assert_uint_eq(header.version_minor, 0);

    bun_close(&ctx);

}
END_TEST

START_TEST(test_bad_magic)
{
#line 72
    assert_bun_status("invalid/01-bad-magic.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_unsupported_version)
{
#line 75
    assert_bun_status("invalid/02-bad-version.bun", BUN_UNSUPPORTED);

}
END_TEST

START_TEST(test_bad_offset_alignment)
{
#line 78
    assert_bun_status("invalid/03-bad-offset-alignment.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_section_past_eof)
{
#line 81
    assert_bun_status("invalid/04-section-past-eof.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_overlapping_sections)
{
#line 84
    assert_bun_status("invalid/05-overlapping-sections.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_asset_name_past_string_table)
{
#line 87
    assert_bun_status("invalid/06-asset-name-past-string-table.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_asset_name_nonprintable)
{
#line 90
    assert_bun_status("invalid/07-asset-name-nonprintable.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_truncated_file)
{
#line 93
    assert_bun_status("invalid/08-truncated-file.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_misaligned_section_size)
{
#line 96
    assert_bun_status("invalid/09-misaligned-section-size.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_overlapping_with_nonprintable)
{
#line 99
    assert_bun_status("invalid/10-overlapping-with-nonprintable.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_second_asset_empty_name)
{
#line 102
    assert_bun_status("invalid/11-second-asset-empty-name.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_asset_name_oob)
{
#line 105
    assert_bun_status("invalid/12-asset-name-oob.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_asset_empty_name)
{
#line 108
    assert_bun_status("invalid/13-asset-empty-name.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_rle_zero_count)
{
#line 111
    assert_bun_status("invalid/14-rle-zero-count.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_rle_bomb)
{
#line 114
    assert_bun_status("invalid/15-rle-bomb.bun", BUN_MALFORMED);

}
END_TEST

START_TEST(test_rle_truncated)
{
#line 117
    assert_bun_status("invalid/16-rle-truncated.bun", BUN_MALFORMED);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, test_valid_minimal);
    tcase_add_test(tc1_1, test_bad_magic);
    tcase_add_test(tc1_1, test_unsupported_version);
    tcase_add_test(tc1_1, test_bad_offset_alignment);
    tcase_add_test(tc1_1, test_section_past_eof);
    tcase_add_test(tc1_1, test_overlapping_sections);
    tcase_add_test(tc1_1, test_asset_name_past_string_table);
    tcase_add_test(tc1_1, test_asset_name_nonprintable);
    tcase_add_test(tc1_1, test_truncated_file);
    tcase_add_test(tc1_1, test_misaligned_section_size);
    tcase_add_test(tc1_1, test_overlapping_with_nonprintable);
    tcase_add_test(tc1_1, test_second_asset_empty_name);
    tcase_add_test(tc1_1, test_asset_name_oob);
    tcase_add_test(tc1_1, test_asset_empty_name);
    tcase_add_test(tc1_1, test_rle_zero_count);
    tcase_add_test(tc1_1, test_rle_bomb);
    tcase_add_test(tc1_1, test_rle_truncated);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
